montana-for-optipeople/waAssembly/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using API;
using API.Data;
using API.Data.Models;
using waAssembly.Filters;

namespace waAssembly.Controllers
{
    [ResetViewBag]
    [dotAuthorize]
    [WorkstationRequired]
    public class OrderController : SiteController
    {

        private DAL ipa = null;
        public OrderController()
        {
            ipa = new DAL();
        }

        protected override void Dispose(bool disposing)
        {
            if (ipa != null)
                ipa.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            return View();
        }

        // partial
        [HttpPost]
        public ActionResult Search(string Phrase)
        {
            var d = ipa.NavInfoSearch(Phrase);
            return PartialView("_search", d);
        }

        // partial
        public ActionResult SearchInProgress() {
            var d = ipa.OrderGetCollectionInProgress();
            return PartialView("_searchInProgress", d);
        }

        public ActionResult Parked()
        {
            //var orders = ipa.OrderParkingGetCollection().OrderBy(m => m.ModifiedByUserID != (CurrentUser?.ID ?? 0)).ToList();
            return View();
        }

        // partial
        [HttpPost]
        public ActionResult SearchParked(string Phrase)
        {
            var orders = ipa.OrderParkingGetCollection().OrderBy(m => m.ModifiedByUserID != (CurrentUser?.ID ?? 0)).ToList();
            if (!string.IsNullOrEmpty(Phrase)) {
                orders = orders.Where(m => m.Barcode.Contains(Phrase)).ToList();
            }
            return PartialView("_searchParked", orders);
        }


        public ActionResult Done()
        {
            return View();
        }

        // partial
        [HttpPost]
        public ActionResult SearchDone(string Phrase)
        {
            var orders = ipa.OrderSearchCompleted(Phrase);
            return PartialView("_searchDone", orders);
        }


        private List<OrderFlowModel> statsGetOrderFlowModels(string BarcodePrefix) {
            List<OrderFlowModel> collection = new List<OrderFlowModel>();
           
            var bars = ipa.NavInfoGetCollectionByOrderPrefix(BarcodePrefix);
            var dicWorkstations = new Dictionary<long, Workstation>();
            foreach (var bar in bars)
            {
                var order = ipa.OrderGetSingle(bar.Barcode);
                var ofm = new OrderFlowModel()
                {
                    Barcode = bar.Barcode
                };
                ofm.TimeLogs = ipa.TimeLogGetCollectionForStats(bar.Barcode).OrderByDescending(m => m.StartTimeUtc).ToList();
                ofm.MarkedCompleted = order?.IsCompleted ?? false;
                ofm.NavInfoDepth = bar.Depth;
                ofm.NavInfoColorSides = bar.Color_sides;

                collection.Add(ofm);
            }
            return collection;
        }

        public ActionResult StatsFlow(string BarcodePrefix) {
            if (!CurrentUser.IsAdmin) {
                return RedirToErrorPage("Not found");
            }

            if (string.IsNullOrEmpty(BarcodePrefix))
            {
                return View(new List<OrderFlowModel>());
            }

            var collection = statsGetOrderFlowModels(BarcodePrefix);
            return View(collection);
        }

        public ActionResult StatsChangeLog(string BarcodePrefix) {
            if (!CurrentUser.IsAdmin)
            {
                return RedirToErrorPage("Not found");
            }

            // load all modules
            // find all change logs
            // find all time logs
            // display

            if (string.IsNullOrEmpty(BarcodePrefix))
            {
                return View(new List<OrderFlowModel>());
            }

            var collection = statsGetOrderFlowModels(BarcodePrefix);
            var changelogs = ipa.OrderChangeLogGetCollection(BarcodePrefix);

            foreach (var item in collection) {
                item.ChangeLogs = changelogs.Where(m => m.Barcode == item.Barcode).ToList();
            }

            return View(collection);
        }

        //public ActionResult Create()
        //{
        //    var model = new UserEditModel();
        //    //model.AvailableOutlets = ipa.OutletGetCollection(CurrentUser.CompanyID);
        //    //model.AvailableCompanies = ipa.CompanyGetCollection();
        //    return View(model);
        //}

        //[HttpPost]
        //public ActionResult Create(UserEditModel model)
        //{
        //    //if (string.IsNullOrEmpty(model.Email) || !dotUtils.RegExp.IsValidEmail(model.Email))
        //    //{
        //    //    ThumbsDown("Enter valid email");
        //    //    return View(model);

        //    //}
        //    //var existing = ipa.UserGetSingle(model.Email.Trim());
        //    //if (existing != null)
        //    //{
        //    //    ThumbsDown("Email already in use by User ID " + existing.ID);
        //    //    return View(model);
        //    //}

        //    if (!ModelState.IsValid) {
        //        ThumbsDown("");
        //        return View(model);
        //    }
        //    var user = new User();
        //    statics.Mapper.Map(model, user);
        //    user = ipa.UserSave(user);

        //    ThumbsUp();
        //    return ReturnToView("Index", model.ID);
        //}

        //public ActionResult Edit(long ID)
        //{
        //    ViewBag.Languages = ipa.LanguageGetCollection().Where(m => m.Active).ToList();
        //    var user = ipa.UserGetSingle(ID);
        //    var model = statics.Mapper.Map<UserEditModel>(user);
        //    //model.CompanyLinks = ipa.CompanyUserTypeLinkGetCollectionByUser(ID);
        //    return View(model);
        //}

        //[HttpPost]
        //public ActionResult Edit(UserEditModel model)
        //{
        //    ViewBag.Languages = ipa.LanguageGetCollection().Where(m => m.Active).ToList();
        //    var user = ipa.UserGetSingle(model.ID);

        //    if (!ModelState.IsValid)
        //    {
        //        ThumbsDown();
        //        return View(model);
        //    }

        //    statics.Mapper.Map(model, user);
        //    user.NameFull = user.FullName;
        //    ipa.UserSave(user);

        //    //ipa.UserClearRoles(user.ID);
        //    //foreach (var roleID in model.SelectedUserRoles)
        //    //{
        //    //    ipa.UserAddRole(user.ID, roleID);
        //    //}

        //    ThumbsUp();
        //    return ReturnToView("Index", model.ID);
        //}

        //public ActionResult Delete(long ID)
        //{
        //    var user = ipa.UserGetSingle(ID);
        //    user.DeletedOnUtc = DateTime.UtcNow;
        //    ipa.UserSave(user);
        //    ThumbsUp();
        //    return RedirectToAction("Index");
        //}


        //public ActionResult Impersonate(long ID)
        //{
        //    var user = ipa.UserGetSingle(ID);
        //    if (user != null && user.Roles.Contains("SBA") && !CurrentUser.HasRole("SBA"))
        //    {
        //        ThumbsDown();
        //        return RedirectToAction("Index", "User");
        //    }

        //    var accountControllerService = SimpleInjectorInitializer.container.GetInstance<AccountService>();
        //    accountControllerService.SetupFormsAuthTicket(ID, false, true, Response, CurrentUser.ID);
        //    ThumbsUp();
        //    return RedirectToAction("Index", "Home", new { area = "" });
        //}

    }
}

montana-for-optipeople/waAssembly/Controllers/PartsController.cs
using API;
using API.Data;
using API.Data.Models;
using System.Web.Mvc;
using waAssembly.Filters;

namespace waAssembly.Controllers
{
    [dotAuthorize]
    [ResetViewBag]
    public class PartsController : SiteController
    {
        private DAL ipa = null;
        public PartsController()
        {
            ipa = new DAL();
        }

        protected override void Dispose(bool disposing)
        {
            if (ipa != null)
            {
                ipa.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string Phrase)
        {
            var d = ipa.PartSearch(Phrase);
            return PartialView("_search", d);
        }

        public ActionResult Create()
        {
            var model = new PartEditModel();
            model.AvailableCategories = ipa.PartCategoryGetCollection();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(PartEditModel model)
        {
            if (!ModelState.IsValid)
            {
                ThumbsDown("");
                model.AvailableCategories = ipa.PartCategoryGetCollection();
                return View(model);
            }

            model.Name = model.Name.Trim();

            var user = new Part();
            statics.Mapper.Map(model, user);
            if (user.PartCategoryID == 0) {
                user.PartCategoryID = null;
            }
            user = ipa.PartSave(user);

            ThumbsUp();
            return ReturnToView("Index", user.ID);
        }

        public ActionResult Edit(long ID)
        {
            var user = ipa.PartGetSingle(ID);
            var model = statics.Mapper.Map<PartEditModel>(user);
            model.AvailableCategories = ipa.PartCategoryGetCollection();
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(PartEditModel model)
        {
            var user = ipa.PartGetSingle(model.ID);

            if (!ModelState.IsValid)
            {
                ThumbsDown();
                model.AvailableCategories = ipa.PartCategoryGetCollection();
                return View(model);
            }

            statics.Mapper.Map(model, user);
            ipa.PartSave(user);

            ThumbsUp();
            return ReturnToView("Index", model.ID);
        }

        public ActionResult Print() {
            return View(ipa.PartGetCollection());
        }

        public ActionResult Delete(int ID) {
            ipa.PartDeletePermanently(ID);
            ThumbsUp();
            return RedirectToAction("Index");
        }
    }
}

montana-for-optipeople/waAssembly/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using API;
using API.Data;
using API.Data.Models;
using waAssembly.Filters;

namespace waAssembly.Controllers
{
    [dotAuthorize(OnlyAdmin = true)]
    [ResetViewBag]
    public class UserController : SiteController
    {

        private DAL ipa = null;
        public UserController()
        {
            ipa = new DAL();
        }

        protected override void Dispose(bool disposing)
        {
            if (ipa != null)
                ipa.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string Phrase)
        {
            var d = ipa.UserSearch(Phrase);
            //if (!CurrentUser.HasRole("SBA"))
            //{
            //    d = d.Where(m => m.CompanyID == CurrentUser.CompanyID).ToList();
            //}
            return PartialView("_search", d);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult SearchUserChange(string Phrase, string ReturnUrl = "")
        {
            var d = ipa.UserSearch(Phrase);
            ViewBag.ReturnUrl = ReturnUrl;
            TempData["ReturnUrl"] = ReturnUrl;
            return PartialView("_searchUserChange", d);
        }

        public ActionResult Create()
        {
            var model = new UserEditModel();
            //model.AvailableOutlets = ipa.OutletGetCollection(CurrentUser.CompanyID);
            //model.AvailableCompanies = ipa.CompanyGetCollection();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(UserEditModel model)
        {
            //if (string.IsNullOrEmpty(model.Email) || !dotUtils.RegExp.IsValidEmail(model.Email))
            //{
            //    ThumbsDown("Enter valid email");
            //    return View(model);

            //}
            //var existing = ipa.UserGetSingle(model.Email.Trim());
            //if (existing != null)
            //{
            //    ThumbsDown("Email already in use by User ID " + existing.ID);
            //    return View(model);
            //}

            if (!ModelState.IsValid) {
                ThumbsDown("");
                return View(model);
            }
            var user = new User();
            statics.Mapper.Map(model, user);
            user = ipa.UserSave(user);

            ThumbsUp();
            return ReturnToView("Index", user.ID);
        }

        public ActionResult Edit(long ID)
        {
            ViewBag.Languages = ipa.LanguageGetCollection().Where(m => m.Active).ToList();
            var user = ipa.UserGetSingle(ID);
            var model = statics.Mapper.Map<UserEditModel>(user);
            //model.CompanyLinks = ipa.CompanyUserTypeLinkGetCollectionByUser(ID);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(UserEditModel model)
        {
            ViewBag.Languages = ipa.LanguageGetCollection().Where(m => m.Active).ToList();
            var user = ipa.UserGetSingle(model.ID);
            
            if (!ModelState.IsValid)
            {
                ThumbsDown();
                return View(model);
            }

            statics.Mapper.Map(model, user);
            user.NameFull = user.FullName;
            ipa.UserSave(user);

            //ipa.UserClearRoles(user.ID);
            //foreach (var roleID in model.SelectedUserRoles)
            //{
            //    ipa.UserAddRole(user.ID, roleID);
            //}

            ThumbsUp();
            return ReturnToView("Index", model.ID);
        }

        public ActionResult Delete(long ID)
        {
            var user = ipa.UserGetSingle(ID);
            user.DeletedOnUtc = DateTime.UtcNow;
            ipa.UserSave(user);
            ThumbsUp();
            return RedirectToAction("Index");
        }

        public ActionResult UpdatePassword(long ID) {
            var user = ipa.UserGetSingle(ID);
            if (user == null) {
                ThumbsDown("User not found");
                return RedirectToAction("Index");
            }

            return View(user);
        }

        [HttpPost]
        public ActionResult UpdatePassword(long ID, string Password, string PasswordRepeat) {
            if (string.IsNullOrEmpty(Password) || Password.Length < 6) {
                ThumbsDown("Passwords must be six (6) characters minimum");
                return RedirectToAction("UpdatePassword", new { ID = ID });
            }

            if (!Password.Equals(PasswordRepeat))
            {
                ThumbsDown("Passwords don't match");
                return RedirectToAction("UpdatePassword", new { ID = ID});
            }
            var user = ipa.UserGetSingle(ID);
            if (user == null)
            {
                ThumbsDown("User not found");
                return RedirectToAction("Index");
            }
            user.Password = Password;
            ipa.UserSave(user);

            ThumbsUp();
            return RedirectToAction("Edit", new { ID = ID });
        }

        
        //public ActionResult Impersonate(long ID)
        //{
        //    var user = ipa.UserGetSingle(ID);
        //    if (user != null && user.Roles.Contains("SBA") && !CurrentUser.HasRole("SBA"))
        //    {
        //        ThumbsDown();
        //        return RedirectToAction("Index", "User");
        //    }

        //    var accountControllerService = SimpleInjectorInitializer.container.GetInstance<AccountService>();
        //    accountControllerService.SetupFormsAuthTicket(ID, false, true, Response, CurrentUser.ID);
        //    ThumbsUp();
        //    return RedirectToAction("Index", "Home", new { area = "" });
        //}

    }
}

montana-for-optipeople/waAssembly/Views/Shared/_Layout.cshtml
@using waAssembly

@{
    string containerClass = "container";
    if (ViewBag.LayoutFluid != null && (bool)ViewBag.LayoutFluid)
    {
        containerClass = "container-fluid";
    }
    // quick'n'dirty:
    string thisurl = this.Request.Url.ToString().ToLower();
    if (!thisurl.Contains("login") && !thisurl.Contains("unauthorized")) {
        statics.App.SetSession(enums.SessionKeys.LastPageVisited, this.Request.Url.ToString());
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewBag.Title - montana assembly</title>

    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="robots" content="noindex, nofollow">

    <script type="text/javascript">
        var globals = {};
        globals.currentUrl = '@Server.UrlDecode(Url.MakeReturnUrl())';
    </script>

    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Libre+Barcode+39+Text" rel="stylesheet" type="text/css" />

    @Url.RenderBundle("waAssembly.css")
    @RenderSection("head", required: false)

</head>
<body>

    <div id="osd"></div>
    <div id="wrapper">
        <!-- <Fixed navbar> -->
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="/">Montana</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fal fa-bars"></i>
            </button>

            @Html.Partial("_navigation")
        </nav>
        <!-- </Fixed navbar> -->
        <!-- <container> -->
        <div id="mainWrapper" class="main-wrapper @(containerClass)" data-ng-app="waAssembly">
            @RenderBody()
        </div>
        <!-- </container> -->

        <div class="spacer"></div>
        <footer></footer>
    </div>

    <div class="modal fade" id="modalUserChange" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@Html.T("User.change")</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group quick-find focus">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-search"></i></span>
                            </div>
                            <input type="text" class="form-control search-phrase" placeholder="@Html.T("placeholderSearch")" />
                            <div class="input-group-append">
                                <span class="input-group-text link index-search-clear" onclick="$(this).closest('.input-group').find('.search-phrase').val('').focus().trigger('input')"><i class="fa fa-times"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="results">

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">@Html.T(TKeys.cancel)</button>
                </div>
            </div>
        </div>
    </div>

    @if (CurrentUser != null) { 
    <div class="modal fade" id="modalUserOptions" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@CurrentUser.Name</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @*<a href="@Url.Action("Logout", "Account", new { stop = false })" class="btn btn-primary btn-block mb-3">
                        <i class="fa fa-sign-out fa-space"></i>
                        @Html.T("logoutAndContinueTimer")
                    </a>
                    <div class="mb-2">&nbsp;</div>*@
                    <a href="@Url.Action("Logout", "Account", new { stop = true })" class="btn btn-secondary btn-block mb-3">
                        <i class="fa fa-sign-out fa-space"></i>
                        @Html.T("logoutAndStopTimer")
                    </a>
                    <div class="mb-2">&nbsp;</div>
                    <a href="@Url.Action("UpdatePassword", "Account")" class="btn btn-default btn-block">
                        <i class="fa fa-key fa-space"></i>
                        @Html.T("User.updatePassword")
                    </a>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">@Html.T(TKeys.cancel)</button>
                </div>
            </div>
        </div>
    </div>
    }

    @Url.RenderBundle("waAssembly.js")

    @RenderSection("scripts", required: false)

</body>
</html>

montana-for-optipeople/waAssembly/Views/Shared/_LayoutDefault.cshtml
@{
    Layout = "_Layout.cshtml";
}

<div class="content-wrapper-main">

    @Html.Partial("_errorDisplayMarkup")

    @if (IsSectionDefined("headerLeft") || IsSectionDefined("headerRight"))
    {
        int cols = 12;
        if (IsSectionDefined("headerLeft") && IsSectionDefined("headerRight"))
        {
            cols = 6;
        }
        <div class="pnl page-header">
            <div class="panel-body">
                <div class="row">
                    @if (IsSectionDefined("headerLeft"))
                    {
                        <div class="col-sm-@cols">
                            <div class="h1">
                                @RenderSection("headerLeft")
                            </div>
                        </div>
                    }

                    @if (IsSectionDefined("headerRight"))
                    {
                        <div class="col-sm-@cols text-right-sm-up header-right">
                            @RenderSection("headerRight")
                        </div>
                    }
                </div>
            </div>
        </div>
    }

    @RenderBody()

</div>



@section head {
    @RenderSection("head", required: false)
}

@section scripts {
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(window).ready(function () { includer(); });
    </script>

    @if (TempData[API.Data.enums.TempDataKeys.ShowOk.ToString()] != null && !String.IsNullOrEmpty(TempData[API.Data.enums.TempDataKeys.ShowOk.ToString()] + ""))
    {
        string msgThumbsUp = "";
        if (!string.IsNullOrEmpty("" + TempData[enums.TempDataKeys.MessageInfo.ToString()]))
        {
            msgThumbsUp = "" + TempData[enums.TempDataKeys.MessageInfo.ToString()];
        }
        else if (!string.IsNullOrEmpty("" + TempData[enums.TempDataKeys.MessageSuccess.ToString()]))
        {
            msgThumbsUp = "" + TempData[enums.TempDataKeys.MessageSuccess.ToString()];
        }

        <script type="text/javascript">$(window).ready(function () { clientside.thumbsUp('@msgThumbsUp'); });</script>
    }
    
    @if (TempData[enums.TempDataKeys.ShowError.ToString()] != null || !String.IsNullOrEmpty(ViewBag.Error))
    {
        <script type="text/javascript">$(window).ready(function () { clientside.thumbsDown(); });</script>
    }

    @*<form id="__aaft" action="#" method="post">@Html.AntiForgeryToken()</form>*@
}

montana-for-optipeople/waAssembly/Views/Shared/_LayoutPrint.cshtml
@using waAssembly

@{
    string containerClass = "container";
    if (ViewBag.LayoutFluid != null && (bool)ViewBag.LayoutFluid)
    {
        containerClass = "container-fluid";
    }
    // quick'n'dirty:
    statics.App.SetSession(enums.SessionKeys.LastPageVisited, this.Request.Url.ToString());
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewBag.Title - montana assembly</title>

    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="robots" content="noindex, nofollow">

    <script type="text/javascript">
        var globals = {};
        globals.currentUrl = '@Server.UrlDecode(Url.MakeReturnUrl())';
    </script>

    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Libre+Barcode+39+Text" rel="stylesheet" type="text/css" />

    @Url.RenderBundle("waAssembly.css")
    @RenderSection("head", required: false)


    <style type="text/css">
        * {
            color: black !important;
            font-size: 16px;
        }
        body {
            background-color: white !important;
        }
        .main-wrapper {
            margin: 0 !important;
            background-color: white !important;
        }
        tr {
            page-break-inside: avoid;
        }
        h3 {
            font-size: 26px;
        }
        .barcode {
            font-size: 56px;
        }
    </style>
</head>
<body>
    <div id="osd"></div>
    <div id="wrapper">
        <!-- <container> -->
        <div id="mainWrapper" class="main-wrapper @(containerClass)" data-ng-app="waAssembly">
            @RenderBody()
        </div>
    </div>
    @Url.RenderBundle("waAssembly.js")
    @RenderSection("scripts", required: false)
</body>
</html>

montana-for-optipeople/waAssembly/Views/Shared/_navigation.cshtml
@{
    TimeLog runningTimer = null;
    if (CurrentUser != null)
    {
        using (var db = new DAL())
        {
            runningTimer = db.TimeLogGetRunning(CurrentUser.ID);
        }
    }
}

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
            <a href="@Url.Action("Index", "Order", new { area = "" })">@Html.T("Order.order")</a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("Parked", "Order", new { area = "" })">@Html.T("Order.parked")</a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("Done", "Order", new { area = "" })">@Html.T("Order.done")</a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("PartsRunner", "Process", new { area = "" })">@Html.T("partsRunner")</a>
        </li>

        @if (!(CurrentUser?.IsAdmin ?? false) && ("" + Session?["adminOk"]) != "true")
        {
            <li class="nav-item">
                <a href="@Url.Action("AdminLogin", "Account")">Admin</a>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a href="@Url.Action("StatsChangeLog", "Order", new { area = "" })">@Html.T("Stats.changeLog")</a>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin</a>
                <ul class="dropdown-menu">
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Dictionary", new { area = "" })">Dictionary</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "User", new { area = "" })">@Html.T("user")</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Workstation", new { area = "" })">@Html.T("workstation")</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "CheckListItem", new { area = "" })">@Html.T("checkListItem")</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "StatusCode", new { area = "" })">@Html.T("statusCode")</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Parts", new { area = "" })">@Html.T("parts")</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "PartCategory", new { area = "" })">@Html.T("partCategory")</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Stats", new { area = "" })">@Html.T("stats")</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("index", "setting", new { area = "" })">Indstillinger</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Abandon", "Account", new { area = "" })">Admin logout</a>
            </li>
        }
    </ul>

    <ul class="my-2 my-lg-0 navbar-nav float-right">
        @if (runningTimer != null)
        {
            <li class="nav-item p-0 pr-3">
                @if (runningTimer.StatusCodeID.HasValue)
                {
                    <a href="@Url.Action("Start", "Process", new { Barcode = runningTimer.Barcode })" class="btn btn-sm btn-danger">
                        <i class="far fa-clock fa-space"></i>
                        @(runningTimer.StatusCode.LocalizedValues.FirstOrDefault(m => m.Language.Locale == Culture)?.Text)
                    </a>
                }
                else
                {
                    <a href="@Url.Action("Running", "Process")" class="btn btn-sm btn-success">
                        <i class="far fa-clock"></i> @Html.T("gotoActiveOrder")
                    </a>
                }
            </li>
        }

        <li class="nav-item p-0">
            @if (CurrentUser == null)
            {
                <a class="btn btn-sm btn-danger nav-user-change"><i class="far fa-user fa-space"></i>@Html.T("login")</a>
            }
            else
            {
                <a class="btn btn-sm btn-primary nav-user-options"><i class="far fa-user fa-space"></i>@CurrentUser.Name</a>
            }
        </li>

        <li class="nav-item p-0">
            <a id="clock"></a>
        </li>
    </ul>
</div>