montana-for-optipeople/waAssembly/Controllers/CheckListItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using API;
using API.Data;
using API.Data.Models;
using waAssembly.Filters;
using waAssembly.Services.Models;

namespace waAssembly.Controllers
{
    [dotAuthorize(OnlyAdmin = true)]
    [ResetViewBag]
    public class CheckListItemController : SiteController
    {

        private DAL ipa = null;
        public CheckListItemController()
        {
            ipa = new DAL();
        }

        protected override void Dispose(bool disposing)
        {
            if (ipa != null)
                ipa.Dispose();
            base.Dispose(disposing);
        }

        private CheckListItemEditModel fixModel(CheckListItemEditModel model)
        {
            var entityType = typeof(CheckListItem).Name;
            model.AvailableLanguages = statics.Cache.LanguagesAll();
            // don't overwrite on postback
            if (model.LocalizedValues == null || !model.LocalizedValues.Any())
            {
                model.LocalizedValues = ipa.LocalizedValueGetCollection(entityType, model.ID);
            }

            foreach (var lang in model.AvailableLanguages)
            {
                if (!model.LocalizedValues.Any(m => m.LanguageID == lang.ID))
                {
                    model.LocalizedValues.Add(new LocalizedValue()
                    {
                        ID = 0,
                        LanguageID = lang.ID,
                        SourceEntityID = model.ID,
                        SourceEntityName = entityType,
                        Text = model.Name
                    });
                }
            }
            return model;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string Phrase)
        {
            var d = ipa.CheckListItemSearch(Phrase);
            //if (!CurrentCheckListItem.HasRole("SBA"))
            //{
            //    d = d.Where(m => m.CompanyID == CurrentCheckListItem.CompanyID).ToList();
            //}
            return PartialView("_search", d);
        }

        [HttpPost]
        public ActionResult SearchAjax(string Phrase)
        {
            var d = ipa.CheckListItemSearch(Phrase);
            return Json(new JsonResultData(JsonResultData.ResultStatus.Ok) { Data = d });
        }

        public ActionResult Create()
        {
            var model = new CheckListItemEditModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CheckListItemEditModel model)
        {
            if (!ModelState.IsValid)
            {
                ThumbsDown("");
                return View(model);
            }
            var entity = new CheckListItem();
            statics.Mapper.Map(model, entity);
            entity = ipa.CheckListItemSave(entity);

            ThumbsUp();
            return ReturnToView("Index", entity.ID);
        }

        public ActionResult Edit(long ID)
        {
            var entity = ipa.CheckListItemGetSingle(ID);
            var model = statics.Mapper.Map<CheckListItemEditModel>(entity);
            model = fixModel(model);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CheckListItemEditModel model)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                model = fixModel(model);
                ThumbsDown();
                return View(model);
            }
            var entity = ipa.CheckListItemGetSingle(model.ID);
            statics.Mapper.Map(model, entity);
            ipa.CheckListItemSave(entity);

            foreach (var localizedValue in model.LocalizedValues)
            {
                ipa.LocalizedValueSave(localizedValue);
            }

            ThumbsUp();
            return ReturnToView("Index", model.ID);
        }

        public ActionResult Delete(long ID)
        {
            ipa.CheckListItemDeletePermanently(ID);
            ThumbsUp();
            return RedirectToAction("Index");
        }


    }
}

montana-for-optipeople/waAssembly/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using API;
using API.Data;
using API.Data.Models;
using waAssembly.Filters;

namespace waAssembly.Controllers
{
    [dotAuthorize(OnlyAdmin = true)]
    [ResetViewBag]
    public class ProductController : SiteController
    {

        private DAL ipa = null;
        public ProductController()
        {
            ipa = new DAL();
        }

        protected override void Dispose(bool disposing)
        {
            if (ipa != null)
                ipa.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string Phrase)
        {
            var d = ipa.ProductSearch(Phrase);
            //if (!CurrentProduct.HasRole("SBA"))
            //{
            //    d = d.Where(m => m.CompanyID == CurrentProduct.CompanyID).ToList();
            //}
            return PartialView("_search", d);
        }

        public ActionResult Create()
        {
            var model = new ProductEditModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ProductEditModel model)
        {
            if (!ModelState.IsValid) {
                ThumbsDown("");
                return View(model);
            }

            model.Name = model.Name.Trim();

            var user = new Product();
            statics.Mapper.Map(model, user);
            user = ipa.ProductSave(user);

            ThumbsUp();
            return ReturnToView("Index", user.ID);
        }

        public ActionResult Edit(long ID)
        {
            var user = ipa.ProductGetSingle(ID);
            var model = statics.Mapper.Map<ProductEditModel>(user);
            model.CheckListItems = ipa.CheckListItemGetCollection(ID);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ProductEditModel model)
        {
            var user = ipa.ProductGetSingle(model.ID);
            
            if (!ModelState.IsValid)
            {
                ThumbsDown();
                return View(model);
            }

            statics.Mapper.Map(model, user);
            ipa.ProductSave(user);

            ipa.LinkProductCheckListItemDeleteByProduct(model.ID);
            int sortOrder = 0;
            foreach (var checkId in model.CheckListItemsPostback) {
                ipa.LinkProductCheckListItemSave(new LinkProductCheckListItem() {
                    CheckListItemID = checkId,
                    ProductID = model.ID,
                    SortOrder = sortOrder++
                });
            }


            ThumbsUp();
            return ReturnToView("Index", model.ID);
        }


        //public ActionResult Import() {

        //    foreach (var name in ipa.NavInfoGetProductNamesUnique().OrderBy(m => m)) {
        //        ipa.ProductSave(new Product() { Name = name });
        //    }
        //    return Content("OK");
        //}

        //public ActionResult Delete(long ID)
        //{
        //    var user = ipa.ProductGetSingle(ID);
        //    user.DeletedOnUtc = DateTime.UtcNow;
        //    ipa.ProductSave(user);
        //    ThumbsUp();
        //    return RedirectToAction("Index");
        //}

    }
}

montana-for-optipeople/waAssembly/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using API;
using API.Data;
using API.Data.Models;
using waAssembly.Filters;

namespace waAssembly.Controllers
{
    [dotAuthorize(OnlyAdmin = true)]
    [ResetViewBag]
    public class UserController : SiteController
    {

        private DAL ipa = null;
        public UserController()
        {
            ipa = new DAL();
        }

        protected override void Dispose(bool disposing)
        {
            if (ipa != null)
                ipa.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string Phrase)
        {
            var d = ipa.UserSearch(Phrase);
            //if (!CurrentUser.HasRole("SBA"))
            //{
            //    d = d.Where(m => m.CompanyID == CurrentUser.CompanyID).ToList();
            //}
            return PartialView("_search", d);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult SearchUserChange(string Phrase, string ReturnUrl = "")
        {
            var d = ipa.UserSearch(Phrase);
            ViewBag.ReturnUrl = ReturnUrl;
            TempData["ReturnUrl"] = ReturnUrl;
            return PartialView("_searchUserChange", d);
        }

        public ActionResult Create()
        {
            var model = new UserEditModel();
            //model.AvailableOutlets = ipa.OutletGetCollection(CurrentUser.CompanyID);
            //model.AvailableCompanies = ipa.CompanyGetCollection();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(UserEditModel model)
        {
            //if (string.IsNullOrEmpty(model.Email) || !dotUtils.RegExp.IsValidEmail(model.Email))
            //{
            //    ThumbsDown("Enter valid email");
            //    return View(model);

            //}
            //var existing = ipa.UserGetSingle(model.Email.Trim());
            //if (existing != null)
            //{
            //    ThumbsDown("Email already in use by User ID " + existing.ID);
            //    return View(model);
            //}

            if (!ModelState.IsValid) {
                ThumbsDown("");
                return View(model);
            }
            var user = new User();
            statics.Mapper.Map(model, user);
            user = ipa.UserSave(user);

            ThumbsUp();
            return ReturnToView("Index", user.ID);
        }

        public ActionResult Edit(long ID)
        {
            ViewBag.Languages = ipa.LanguageGetCollection().Where(m => m.Active).ToList();
            var user = ipa.UserGetSingle(ID);
            var model = statics.Mapper.Map<UserEditModel>(user);
            //model.CompanyLinks = ipa.CompanyUserTypeLinkGetCollectionByUser(ID);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(UserEditModel model)
        {
            ViewBag.Languages = ipa.LanguageGetCollection().Where(m => m.Active).ToList();
            var user = ipa.UserGetSingle(model.ID);
            
            if (!ModelState.IsValid)
            {
                ThumbsDown();
                return View(model);
            }

            statics.Mapper.Map(model, user);
            user.NameFull = user.FullName;
            ipa.UserSave(user);

            //ipa.UserClearRoles(user.ID);
            //foreach (var roleID in model.SelectedUserRoles)
            //{
            //    ipa.UserAddRole(user.ID, roleID);
            //}

            ThumbsUp();
            return ReturnToView("Index", model.ID);
        }

        public ActionResult Delete(long ID)
        {
            var user = ipa.UserGetSingle(ID);
            user.DeletedOnUtc = DateTime.UtcNow;
            ipa.UserSave(user);
            ThumbsUp();
            return RedirectToAction("Index");
        }

        public ActionResult UpdatePassword(long ID) {
            var user = ipa.UserGetSingle(ID);
            if (user == null) {
                ThumbsDown("User not found");
                return RedirectToAction("Index");
            }

            return View(user);
        }

        [HttpPost]
        public ActionResult UpdatePassword(long ID, string Password, string PasswordRepeat) {
            if (string.IsNullOrEmpty(Password) || Password.Length < 6) {
                ThumbsDown("Passwords must be six (6) characters minimum");
                return RedirectToAction("UpdatePassword", new { ID = ID });
            }

            if (!Password.Equals(PasswordRepeat))
            {
                ThumbsDown("Passwords don't match");
                return RedirectToAction("UpdatePassword", new { ID = ID});
            }
            var user = ipa.UserGetSingle(ID);
            if (user == null)
            {
                ThumbsDown("User not found");
                return RedirectToAction("Index");
            }
            user.Password = Password;
            ipa.UserSave(user);

            ThumbsUp();
            return RedirectToAction("Edit", new { ID = ID });
        }

        
        //public ActionResult Impersonate(long ID)
        //{
        //    var user = ipa.UserGetSingle(ID);
        //    if (user != null && user.Roles.Contains("SBA") && !CurrentUser.HasRole("SBA"))
        //    {
        //        ThumbsDown();
        //        return RedirectToAction("Index", "User");
        //    }

        //    var accountControllerService = SimpleInjectorInitializer.container.GetInstance<AccountService>();
        //    accountControllerService.SetupFormsAuthTicket(ID, false, true, Response, CurrentUser.ID);
        //    ThumbsUp();
        //    return RedirectToAction("Index", "Home", new { area = "" });
        //}

    }
}

montana-for-optipeople/waAssembly/Views/Product/Create.cshtml
@model API.Data.Models.ProductEditModel
@{
    ViewBag.Title = Html.T(TKeys.Product.product);
}

@section headerLeft {
    @ViewBag.Title
    <span class="h1-sub"></span>
}

@section headerRight {
    <div>
        <a href="@Url.Action("Index")" class="btn btn-sm btn-default ays-cancel"><i class="fa fa-arrow-left fa-space"></i>@Html.T("back")</a>
    </div>
}

<div class="pnl">
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            <div class="form-group focus">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>

            @Html.Partial("_buttonsRow", new waAssembly.Models.ButtonsModel() {}, new ViewDataDictionary())
        }


    </div>
</div>

@section scripts {

}

montana-for-optipeople/waAssembly/Views/Product/Edit.cshtml
@model API.Data.Models.ProductEditModel
@{
    ViewBag.Title = Html.T(TKeys.Product.product);
}

@section headerLeft {
    @ViewBag.Title
    <span class="h1-sub"></span>
}

@section headerRight {
    <div>
        @if (CurrentUser?.HasRole("SBA") ?? false)
        {
            <a class="btn btn-sm btn-default" href="@Url.Action("Impersonate", "User", new { ID = Model.ID })">Impersonate</a>
        }
        <a class="btn btn-sm btn-default inline-danger inline-confirm"><i class="fa fa-trash-alt fa-space"></i>@Html.T("delete")</a>
        <a href="@Url.Action("Delete", new { ID = Model.ID })" class="btn btn-sm btn-danger hidden"><i class="fa fa-trash-alt fa-space"></i>@Html.T("confirmDelete")</a>


        <a href="@Url.Action("Index")" class="btn btn-sm btn-default ays-cancel"><i class="fa fa-arrow-left fa-space"></i>@Html.T("back")</a>
    </div>
}

<div class="pnl" data-ng-controller="editController" id="editControllerContainer">
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary()
            @Html.HiddenFor(m => m.ID)

            <div class="form-group focus">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>

            <hr />

            <div class="row">
                <div class="col-6">
                    <label>Tilgængelige checklistepunkter</label>
                    <input type="text" id="inpChecklistPhrase" class="form-control mb-2" data-ng-keyup="search()" data-ng-model="searchPhrase" placeholder="@Html.T("placeholderSearch")" autocomplete="off" />
                    
                    <div class="related-item link" ng-repeat="item in searchResultsChecklistItems" data-ng-click="checklistAdd(item)">
                        
                        <a class="btn btn-success fa-space"><i class="far fa-plus"></i></a>
                        <a>{{item.Name}}</a>
                    </div>

                </div>
                <div class="col-6">
                    <label>Valgte checklistepunkter</label>
                    <div>
                        <div class="related-item" ng-repeat="item in checklistItems">
                            <a class="btn btn-danger fa-space" data-ng-click="checklistRemove(item)"><i class="far fa-trash"></i></a>
                            <a data-ng-href="@Url.Action("Edit", "CheckListItem")/{{item.ID}}">{{item.Name | limitTo: 45 }}</a>
                            
                            <span class="float-right">
                                <a class="btn btn-default float-right" data-ng-click="checklistReorder(item, 0)" data-ng-class="{ invisible: $index == 0 }"><i title="up" class="fa fa-caret-up"></i></a>

                                <a class="btn btn-default float-right" data-ng-click="checklistReorder(item, -1)" data-ng-class="{ invisible: $index == checklistItems.length - 1}"><i title="down" class="fa fa-caret-down"></i></a>
                            </span>
                            
                        </div>
                    </div>

                    <div data-ng-repeat="element in checklistItems">
                        <input type="hidden" name="CheckListItemsPostback" value="{{element.ID}}" />
                    </div>

                </div>
            </div>

            @Html.Partial("_buttonsRow", new ButtonsModel() { }, new ViewDataDictionary())
        }


    </div>
</div>

@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.min.js"></script>
    <script>
        globals.angSearchUrl = '@(Url.Action("SearchAjax", "ChecklistItem"))';
		globals.checklistItems = @Html.Raw(statics.ToJson(Model.CheckListItems));
    </script>
    <script src="~/assets/js/page/product-edit.js"></script>
}

montana-for-optipeople/waAssembly/Views/Product/Index.cshtml
@{
    ViewBag.Title = Html.T(TKeys.Product.product);
}

<div class="pnl">
    <div class="panel-body">
        <div class="h1">
            @ViewBag.Title
            <div>
                <a href="@Url.Action("Create")" class="btn btn-sm btn-success">@Html.T("createNew")</a>
            </div>
        </div>
        <div class="form-group quick-find focus">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-search"></i></span>
                </div>
                <input type="text" class="form-control" id="indexSearch" placeholder="@Html.T("placeholderSearch")" />
                <div class="input-group-append">
                    <span class="input-group-text link index-search-clear"><i class="fa fa-times"></i></span>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="xresults" class="pnl hidden">
    <div class="panel-body">
        <div id="results">
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript" src="~/assets/js/base/indexSearcher-4.js"></script>
    <script type="text/javascript">
		$(function () {
			$('#indexSearch').indexSearcher(
				{
					endpoint: '@Url.Action("Index")/Search'
					,resultsElement: '#results'
					//,ajaxAdditionalData: { Archive: false }
				}
			);
		})
    </script>
}

montana-for-optipeople/waAssembly/Views/Product/_search.cshtml
@model List<API.Data.Product>
@{
}

@if (Model == null || !Model.Any())
{
<div class="alert alert-danger">
    @Html.T("nodata")
</div>
}
else
{
	<div class="panel panel-list">
		<ul class="list-row list-row-header">
			<li>ID</li>
			<li>@Html.T("name")</li>
		</ul>

		@foreach (var item in Model)
		{
			<ul class="list-row" data-clickurl="@Url.Action("Edit", new { ID = item.ID })">
				<li>
					@item.ID
				</li>
				<li>
					<a href="@Url.Action("Edit", new { ID = item.ID })">@item.Name</a>
				</li>
			</ul>
		}
	</div>
}


@section scripts {

}